In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from collections import Counter

In [2]:
nome_xls = 'excel'
arquivos_xls = 1
nome_df = 'dataset_cigarro'

df_total = pd.concat([
    pd.read_excel(f"{nome_xls}{i}.xls")
    for i in range(1, arquivos_xls + 1)
], ignore_index=True)

df_total = df_total.dropna(subset='DOI')
display(df_total)

,Publication Type,Authors,Book Authors,Book Editors,Book Group Authors,Author Full Names,Book Author Full Names,Group Authors,Article Title,Source Title,...,Web of Science Index,Research Areas,IDS Number,Pubmed Id,Open Access Designations,Highly Cited Status,Hot Paper Status,Date of Export,UT (Unique WOS ID),Web of Science Record
0,J,"Kurmus, H; Mohajerani, A",NaN,NaN,NaN,"Kurmus, Halenur; Mohajerani, Abbas",NaN,NaN,The toxicity and valorization options of cigar...,WASTE MANAGEMENT,...,Science Citation Index Expanded (SCI-EXPANDED),Engineering; Environmental Sciences & Ecology,KM9EN,31978829.0,NaN,NaN,NaN,2025-08-17,WOS:000514444500012,0
1,J,"Gill, H; Rogers, K; Rehman, B; Moynihan, J; Be...",NaN,NaN,NaN,"Gill, Hussan; Rogers, Kyler; Rehman, Bilal; Mo...",NaN,NaN,Cigarette butts may have low toxicity to soil-...,SCIENCE OF THE TOTAL ENVIRONMENT,...,Science Citation Index Expanded (SCI-EXPANDED),Environmental Sciences & Ecology,GG1QP,29454197.0,NaN,NaN,NaN,2025-08-17,WOS:000432462000058,0
2,J,"Moroz, I; Scapolio, LGB; Cesarino, I; Leao, AL...",NaN,NaN,NaN,"Moroz, Ivan; Scapolio, Luiz G. B.; Cesarino, I...",NaN,NaN,Toxicity of cigarette butts and possible recyc...,ENVIRONMENTAL SCIENCE AND POLLUTION RESEARCH,...,Science Citation Index Expanded (SCI-EXPANDED),Environmental Sciences & Ecology,QI2QM,33411271.0,NaN,NaN,NaN,2025-08-17,WOS:000607363600031,0
3,J,"Lee, W; Lee, CC",NaN,NaN,NaN,"Lee, Wenjau; Lee, Chih Chun",NaN,NaN,Developmental toxicity of cigarette butts - An...,ECOTOXICOLOGY AND ENVIRONMENTAL SAFETY,...,Science Citation Index Expanded (SCI-EXPANDED),Environmental Sciences & Ecology; Toxicology,CA5RV,25531833.0,NaN,NaN,NaN,2025-08-17,WOS:000348966400043,0
4,J,"Werdel, GM; Pandey, LK; Bergey, EA",NaN,NaN,NaN,"Werdel, Gina M.; Pandey, Lalit K.; Bergey, Eli...",NaN,NaN,Cigarette butt effects on diatom health in a s...,AQUATIC ECOLOGY,...,Science Citation Index Expanded (SCI-EXPANDED),Environmental Sciences & Ecology; Marine & Fre...,TW9CU,NaN,NaN,NaN,NaN,2025-08-17,WOS:000675053900001,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,J,"Seuront, L; Zardi, G; Uguen, M; Bouchet, VMP; ...",NaN,NaN,NaN,"Seuront, Laurent; Zardi, Gerardo, I; Uguen, Ma...",NaN,NaN,A whale of a plastic tale: A plea for interdis...,SCIENCE OF THE TOTAL ENVIRONMENT,...,Science Citation Index Expanded (SCI-EXPANDED),Environmental Sciences & Ecology,4N5ZU,35868387.0,"Bronze, Green Published",NaN,NaN,2025-08-17,WOS:000854099100002,0
159,J,"Yalwaji, B; John-Nwagwu, HO; Sogbanmu, TO",NaN,NaN,NaN,"Yalwaji, B.; John-Nwagwu, H. O.; Sogbanmu, T. O.",NaN,NaN,Plastic pollution in the environment in Nigeri...,SCIENTIFIC AFRICAN,...,Emerging Sources Citation Index (ESCI),Science & Technology - Other Topics,1X2TF,NaN,gold,NaN,NaN,2025-08-17,WOS:000807311700001,0
160,J,"Kachef, RL; Chadwick, MA",NaN,NaN,NaN,"Kachef, Randa L.; Chadwick, Michael A.",NaN,NaN,Litter impact index: A proposed weighting of l...,JOURNAL OF CLEANER PRODUCTION,...,Science Citation Index Expanded (SCI-EXPANDED),Science & Technology - Other Topics; Engineeri...,Y4O3S,NaN,hybrid,NaN,NaN,2025-08-17,WOS:001431933000001,0
161,J,"De Frond, HL; van Sebille, E; Parnis, JM; Diam...",NaN,NaN,NaN,"De Frond, Hannah L.; van Sebille, Erik; Parnis...",NaN,NaN,Estimating the Mass of Chemicals Associated wi...,INTEGRATED ENVIRONMENTAL ASSESSMENT AND MANAGE...,...,Science Citation Index Expanded (SCI-EXPANDED),Environmental Sciences & Ecology; Toxicology,IM0HQ,30900806.0,Green Published,NaN,NaN,2025-08-17,WOS:000477668500012,0
162,J,"Asensio-Montesinos, F; Anfuso, G; Aguilar-Torr...",NaN,NaN,NaN,"Asensio-Montesinos, Francisco; Anfuso, Giorgio...",NaN,NaN,Abundance and Temporal Distribution of Beach L...,WATER,...,Science Citation Index Expanded (SCI-EXPANDED),Environmental Sciences & Ecology; Water Resources,2A9IZ,NaN,"Green Published, gold",NaN,NaN,2025-08-17,WOS:000809810000001,0

In [3]:
df_scopus = pd.read_csv('scopus.csv')
df_scopus

,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,...,ISBN,CODEN,PubMed ID,Language of Original Document,Abbreviated Source Title,Document Type,Publication Stage,Open Access,Source,EID
0,Werdel G.M.; Pandey L.K.; Bergey E.A.,"Werdel, Gina M. (57226194869); Pandey, Lalit K...",57226194869; 57193624033; 7003864609,Cigarette butt effects on diatom health in a s...,2021,Aquatic Ecology,55,3,NaN,999.0,...,NaN,AQECF,NaN,English,Aquatic Ecol.,Article,Final,NaN,Scopus,2-s2.0-85110902551
1,Dolar A.; Mušič B.; Skalar T.; Marolt G.; Drob...,"Dolar, Andraž (57211536324); Mušič, Branka (53...",57211536324; 53880311300; 55037503100; 5812809...,Microplastics from cigarette filters: Comparat...,2025,Environmental Pollution,374,NaN,126199,NaN,...,NaN,ENPOE,40185183.0,English,Environ. Pollut.,Article,Final,NaN,Scopus,2-s2.0-105001969105
2,Novotny T.E.; Hamzai L.,"Novotny, Thomas E. (35551723100); Hamzai, Lail...",35551723100; 57226357137,Cellulose acetate cigarette filter is hazardou...,2024,Tobacco Control,33,5,NaN,663.0,...,NaN,NaN,37072169.0,English,Tob. Control,Article,Final,All Open Access; Green Open Access,Scopus,2-s2.0-85159214281
3,Bergey E.A.; Shakir M.F.,"Bergey, Elizabeth A. (7003864609); Shakir, Mar...",7003864609; 57787961600,"In a behavioural bioassay, effluents from ciga...",2022,Journal of Molluscan Studies,88,2,eyac014,NaN,...,NaN,JMSTD,NaN,English,J. Molluscan Stud.,Article,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-85133605403
4,Howlader M.; Selim A.; Shuvo S.N.A.; Islam M.M...,"Howlader, Masum (58566004700); Selim, Abu (585...",58566004700; 58565489600; 58565489700; 5949932...,Evaluating cigarette butt pollution: Insights ...,2023,Marine Pollution Bulletin,197,NaN,115705,NaN,...,NaN,MPNBA,NaN,English,Mar. Pollut. Bull.,Article,Final,NaN,Scopus,2-s2.0-85175208867
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,Borys D.J.; Setzer S.C.; Ling L.J.,"Borys, D.J. (6701752834); Setzer, S.C. (660369...",6701752834; 6603691280; 7202813694,CNS depression in an infant after the ingestio...,1988,Veterinary and Human Toxicology,30,1,NaN,20.0,...,NaN,VHTOD,3354177.0,English,VET. HUM. TOXICOL.,Article,Final,NaN,Scopus,2-s2.0-0023867183
101,Smolinske S.C.; Spoerke D.G.; Spiller S.K.; Wr...,"Smolinske, S.C. (6603630470); Spoerke, D.G. (6...",6603630470; 6701686514; 7801642793; 6602908712...,Cigarette and Nicotine Chewing Gum Toxicity in...,1988,Human & Experimental Toxicology,7,1,NaN,27.0,...,NaN,NaN,3346035.0,English,Hum. Exp. Toxicol.,Article,Final,NaN,Scopus,2-s2.0-84965916704
102,Tseng P.J.,"Tseng, Pablo J. (26039501400)",26039501400,Human exposure to perfluorinated compounds via...,2009,Journal of Applied Sciences,9,13,NaN,2475.0,...,NaN,NaN,NaN,English,J. Appl. Sci.,Article,Final,NaN,Scopus,2-s2.0-67649432768
103,Micevska T.; Warne M.St.J.; Pablo F.; Patra R.,"Micevska, T. (15834844400); Warne, M.St.J. (57...",15834844400; 57153693100; 6701703370; 17135735400,"Variation in, and causes of, toxicity of cigar...",2006,Archives of Environmental Contamination and To...,50,2,NaN,205.0,...,NaN,AECTC,16328625.0,English,Arch. Environ. Contam. Toxicol.,Article,Final,NaN,Scopus,2-s2.0-31544477486
104,McGee D.; Brabson T.; McCarthy J.; Picciotti M.,"McGee, Douglas (16171841100); Brabson, Thomas ...",16171841100; 7801648107; 57223811844; 6603945761,Four-year review of cigarette ingestions in ch...,1995,Pediatric Emergency Care,11,1,NaN,13.0,...,NaN,NaN,7739954.0,English,Pediatr. Emerg. Care,Article,Final,NaN,Scopus,2-s2.0-0028953148

In [4]:
abstracts = list(df_total["Abstract"]) + list(df_scopus["Abstract"])
titulos = list(df_total["Article Title"]) + list(df_scopus["Title"])
dois = list(df_total["DOI"]) + list(df_scopus["DOI"])
autores = list(df_total["Authors"]) + list(df_scopus["Authors"])
anos = list(df_total["Publication Year"]) + list(df_scopus["Year"])
wos_id = wos_id = list(df_total["UT (Unique WOS ID)"]) + list(df_scopus["EID"])
artigo_id = []

for i in range(len(abstracts)):
    a = i + 1
    artigo_id.append(a)

resultados = {
    "title": titulos,
    "authors": autores,
    "abstract": abstracts,
    "DOI": dois,
    "year": anos,
    "article_id": artigo_id,
    "wos_id": wos_id
}

df = pd.DataFrame(resultados)

In [5]:
len(df)

265

In [8]:
df = df.drop_duplicates(subset=["DOI"])
df = df.drop_duplicates(subset=["title"])

In [9]:
len(df)

186

In [12]:
df.dropna(subset=["DOI"], inplace=True)

In [13]:
df

,title,authors,abstract,DOI,year,article_id,wos_id
0,The toxicity and valorization options of cigar...,"Kurmus, H; Mohajerani, A","Cigarette butts, one of the most abundant form...",10.1016/j.wasman.2020.01.011,2020,1,WOS:000514444500012
1,Cigarette butts may have low toxicity to soil-...,"Gill, H; Rogers, K; Rehman, B; Moynihan, J; Be...",Cigarette butts are a common form of litter th...,10.1016/j.scitotenv.2018.02.080,2018,2,WOS:000432462000058
2,Toxicity of cigarette butts and possible recyc...,"Moroz, I; Scapolio, LGB; Cesarino, I; Leao, AL...","Tobacco is a worldwide-consumed product, which...",10.1007/s11356-020-11856-z,2021,3,WOS:000607363600031
3,Developmental toxicity of cigarette butts - An...,"Lee, W; Lee, CC",Cigarette butts (CBs) littering is not just an...,10.1016/j.ecoenv.2014.12.018,2015,4,WOS:000348966400043
4,Cigarette butt effects on diatom health in a s...,"Werdel, GM; Pandey, LK; Bergey, EA",Cigarette butts are a prevalent form of litter...,10.1007/s10452-021-09876-z,2021,5,WOS:000675053900001
...,...,...,...,...,...,...,...
241,Cigarette butts in Vietnam's marine environmen...,Thuan P.M.; Nguyen M.-K.; Lin C.; Rangel-Buitr...,Cigarette butts contain over 4000 toxic chemic...,10.1016/j.scitotenv.2024.177484,2024,242,2-s2.0-85209106164
244,Assessment of the release of metals from cigar...,Roselli C.; Fagiolino I.; Desideri D.; Sisti D...,Cigarette butts are known to contain toxic met...,10.1371/journal.pone.0260111,2021,245,2-s2.0-85120032635
250,Effects of Cigarette Butt Leachate on the Grow...,Ajibade S.; Simon B.; Takács A.; Gulyás M.,Cigarette butts (CBs) are emerging soil contam...,10.3390/pollutants4040035,2024,251,2-s2.0-105004350733
258,A review of environmental pollution from the u...,Beutel M.W.; Harmon T.C.; Novotny T.E.; Mock J...,While the impacts of cigarette smoking on huma...,10.3390/su132312994,2021,259,2-s2.0-85120061574
262,Human exposure to perfluorinated compounds via...,Tseng P.J.,The current study investigates the potential o...,10.3923/jas.2009.2475.2479,2009,263,2-s2.0-67649432768

In [11]:
df.to_excel(f"{nome_df}.xlsx", index=False)
print(f"Saved '{nome_df}.xlsx'.")

Saved 'dataset_cigarro.xlsx'.